const i18n={
en:{
"nav.dashboard":"Dashboard","nav.pipeline":"Pipeline","nav.contacts":"Contacts","nav.tasks":"Tasks","sidebar.demo":"Portfolio Demo","sidebar.local":"Data stored locally in your browser","user.role":"Administrator","actions.newLead":"New lead",
"hero.eyebrow":"SALES WORKSPACE","hero.title":"Keep every opportunity moving.","hero.text":"Track leads, priorities and follow-ups from one simple workspace.","hero.cta":"Open pipeline",
"metrics.pipeline":"Total pipeline","metrics.pipelineDesc":"Value of all open opportunities","metrics.active":"Active leads","metrics.activeDesc":"Opportunities still in progress","metrics.closeRate":"Close rate","metrics.closeRateDesc":"Won deals compared with the total","metrics.revenue":"Won revenue","metrics.month":"This month","metrics.revenueDesc":"Value of opportunities marked as won",
"dashboard.pipelineTitle":"Sales pipeline","dashboard.pipelineDesc":"Distribution of opportunities by stage.","dashboard.viewPipeline":"View pipeline →","dashboard.activityTitle":"Recent activity","dashboard.activityDesc":"Latest updates in the CRM.","dashboard.hotLeads":"Priority leads","dashboard.hotLeadsDesc":"High-value opportunities requiring attention.",
"table.lead":"Lead","table.company":"Company","table.value":"Value","table.stage":"Stage","table.owner":"Owner",
"pipeline.title":"Sales Pipeline","pipeline.subtitle":"Move opportunities between stages and track progress.","pipeline.all":"All opportunities","pipeline.high":"High value",
"contacts.title":"Contacts","contacts.subtitle":"People and companies connected to your opportunities.","tasks.title":"Tasks","tasks.subtitle":"Follow-ups and actions linked to your sales work.","tasks.new":"New task",
"modal.newOpportunity":"NEW OPPORTUNITY","modal.addLead":"Add lead","form.name":"Contact name","form.company":"Company","form.value":"Opportunity value","form.stage":"Stage","form.email":"E-mail","form.saveLead":"Save lead",
"tasks.newTaskLabel":"NEW TASK","tasks.createTask":"Create task","tasks.taskTitle":"Task title","tasks.due":"Due date","tasks.save":"Save task",
"titles.dashboard":["Dashboard","Overview of your sales activity."],"titles.pipeline":["Pipeline","Manage opportunities across the sales process."],"titles.contacts":["Contacts","Customers and companies in your network."],"titles.tasks":["Tasks","Follow-ups and activities that need attention."],
"search":"Search lead or company","stages.new":"New","stages.qualified":"Qualified","stages.proposal":"Proposal","stages.negotiation":"Negotiation","stages.won":"Won",
"activity.added":"New opportunity added","activity.moved":"Opportunity stage updated","toast.lead":"Lead added successfully.","toast.task":"Task created.","toast.moved":"Opportunity moved.","toast.deleted":"Task removed.","tasks.noTasks":"No tasks yet.","contacts.noContacts":"No contacts found."
},
pt:{
"nav.dashboard":"Painel","nav.pipeline":"Pipeline","nav.contacts":"Contactos","nav.tasks":"Tarefas","sidebar.demo":"Demonstração de Portfólio","sidebar.local":"Dados guardados localmente no navegador","user.role":"Administrador","actions.newLead":"Novo lead",
"hero.eyebrow":"ÁREA COMERCIAL","hero.title":"Mantém cada oportunidade em movimento.","hero.text":"Acompanha leads, prioridades e seguimentos num único espaço de trabalho.","hero.cta":"Abrir pipeline",
"metrics.pipeline":"Pipeline total","metrics.pipelineDesc":"Valor de todas as oportunidades abertas","metrics.active":"Leads activos","metrics.activeDesc":"Oportunidades ainda em andamento","metrics.closeRate":"Taxa de fecho","metrics.closeRateDesc":"Negócios ganhos em relação ao total","metrics.revenue":"Receita ganha","metrics.month":"Este mês","metrics.revenueDesc":"Valor das oportunidades marcadas como ganhas",
"dashboard.pipelineTitle":"Pipeline comercial","dashboard.pipelineDesc":"Distribuição das oportunidades por fase.","dashboard.viewPipeline":"Ver pipeline →","dashboard.activityTitle":"Actividade recente","dashboard.activityDesc":"Últimas alterações no CRM.","dashboard.hotLeads":"Leads prioritários","dashboard.hotLeadsDesc":"Oportunidades de maior valor que exigem atenção.",
"table.lead":"Lead","table.company":"Empresa","table.value":"Valor","table.stage":"Fase","table.owner":"Responsável",
"pipeline.title":"Pipeline de Vendas","pipeline.subtitle":"Move oportunidades entre fases e acompanha o progresso.","pipeline.all":"Todas as oportunidades","pipeline.high":"Alto valor",
"contacts.title":"Contactos","contacts.subtitle":"Pessoas e empresas ligadas às tuas oportunidades.","tasks.title":"Tarefas","tasks.subtitle":"Acompanhamentos e acções ligadas ao trabalho comercial.","tasks.new":"Nova tarefa",
"modal.newOpportunity":"NOVA OPORTUNIDADE","modal.addLead":"Adicionar lead","form.name":"Nome do contacto","form.company":"Empresa","form.value":"Valor da oportunidade","form.stage":"Fase","form.email":"E-mail","form.saveLead":"Guardar lead",
"tasks.newTaskLabel":"NOVA TAREFA","tasks.createTask":"Criar tarefa","tasks.taskTitle":"Título da tarefa","tasks.due":"Data limite","tasks.save":"Guardar tarefa",
"titles.dashboard":["Painel","Visão geral da actividade comercial."],"titles.pipeline":["Pipeline","Gere oportunidades ao longo do processo de vendas."],"titles.contacts":["Contactos","Clientes e empresas da tua rede."],"titles.tasks":["Tarefas","Acompanhamentos e actividades que precisam de atenção."],
"search":"Pesquisar lead ou empresa","stages.new":"Novo","stages.qualified":"Qualificado","stages.proposal":"Proposta","stages.negotiation":"Negociação","stages.won":"Ganho",
"activity.added":"Nova oportunidade adicionada","activity.moved":"Fase da oportunidade actualizada","toast.lead":"Lead adicionado com sucesso.","toast.task":"Tarefa criada.","toast.moved":"Oportunidade movida.","toast.deleted":"Tarefa removida.","tasks.noTasks":"Ainda não existem tarefas.","contacts.noContacts":"Nenhum contacto encontrado."
}};
const defaultLeads=[
{id:1,name:"Amina Costa",company:"MobiTech Lda",email:"amina@mobitech.co.mz",value:125000,stage:"proposal",owner:"Francisco",score:92,avatar:"amina"},
{id:2,name:"James Carter",company:"Northstar Labs",email:"james@northstar.io",value:78000,stage:"qualified",owner:"Francisco",score:84,avatar:"james"},
{id:3,name:"Paulo Mucavele",company:"Solar Grid",email:"paulo@solargrid.co.mz",value:196000,stage:"negotiation",owner:"Francisco",score:96,avatar:"paulo"},
{id:4,name:"Sofia Martins",company:"Atlas Digital",email:"sofia@atlas.digital",value:54000,stage:"new",owner:"Francisco",score:73,avatar:"sofia"},
{id:5,name:"Liam Brown",company:"Orbit Systems",email:"liam@orbit.systems",value:143000,stage:"proposal",owner:"Francisco",score:88,avatar:"liam"},
{id:6,name:"Helena Matola",company:"Moz Logistics",email:"helena@mozlogistics.co.mz",value:91000,stage:"qualified",owner:"Francisco",score:81,avatar:"helena"},
{id:7,name:"Daniel Smith",company:"Vertex Cloud",email:"daniel@vertex.cloud",value:168000,stage:"won",owner:"Francisco",score:95,avatar:"daniel"},
{id:8,name:"Inês Nhantumbo",company:"GreenRoute",email:"ines@greenroute.co.mz",value:67000,stage:"new",owner:"Francisco",score:76,avatar:"ines"}];
const defaultTasks=[
{id:1,title:"Follow up with Solar Grid",date:"2026-09-24",done:false},
{id:2,title:"Send proposal to Northstar Labs",date:"2026-09-25",done:false},
{id:3,title:"Prepare onboarding for Vertex Cloud",date:"2026-09-26",done:true}];
const stages=["new","qualified","proposal","negotiation","won"];
let leads=JSON.parse(localStorage.getItem("clientflowLeads")||"null")||defaultLeads;
let tasks=JSON.parse(localStorage.getItem("clientflowTasks")||"null")||defaultTasks;
let lang=localStorage.getItem("clientflowLang")||"en",currentView="dashboard",search="";
const $=id=>document.getElementById(id);const t=key=>i18n[lang][key]??key;const money=n=>new Intl.NumberFormat(lang==="pt"?"pt-MZ":"en-US").format(n)+" MT";
function save(){localStorage.setItem("clientflowLeads",JSON.stringify(leads));localStorage.setItem("clientflowTasks",JSON.stringify(tasks))}
function setLanguage(next){lang=next;localStorage.setItem("clientflowLang",lang);document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(i18n[lang][k])el.textContent=i18n[lang][k]});$("searchInput").placeholder=t("search");$("langEN").classList.toggle("active",lang==="en");$("langPT").classList.toggle("active",lang==="pt");updatePageTitle();renderAll()}
function updatePageTitle(){const [title,sub]=t("titles."+currentView);$("pageTitle").textContent=title;$("pageSubtitle").textContent=sub}
function setView(view){currentView=view;document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll(".nav-item").forEach(v=>v.classList.toggle("active",v.dataset.view===view));$(view+"View").classList.add("active");updatePageTitle();closeSidebar()}
function filteredLeads(){return leads.filter(l=>`${l.name} ${l.company} ${l.email}`.toLowerCase().includes(search.toLowerCase()))}
function animateNumber(el,to,suffix=""){const start=0,duration=500,t0=performance.now();function tick(now){const p=Math.min((now-t0)/duration,1);const value=Math.round(start+(to-start)*(1-Math.pow(1-p,3)));el.textContent=value+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function renderMetrics(){const open=leads.filter(l=>l.stage!=="won"),won=leads.filter(l=>l.stage==="won");$("totalPipeline").textContent=money(open.reduce((s,l)=>s+l.value,0));animateNumber($("activeLeads"),open.length);animateNumber($("closeRate"),Math.round((won.length/Math.max(leads.length,1))*100),"%");$("wonRevenue").textContent=money(won.reduce((s,l)=>s+l.value,0))}
function renderFunnel(){const openStages=stages.slice(0,4),max=Math.max(...openStages.map(s=>leads.filter(l=>l.stage===s).reduce((sum,l)=>sum+l.value,0)),1);$("funnelList").innerHTML=openStages.map(stage=>{const val=leads.filter(l=>l.stage===stage).reduce((sum,l)=>sum+l.value,0),pct=Math.max(8,Math.round(val/max*100));return `<div class="funnel-row"><span class="funnel-label">${t("stages."+stage)}</span><div class="funnel-track"><div class="funnel-fill" style="width:${pct}%"></div></div><span class="funnel-value">${money(val)}</span></div>`}).join("")}
function renderActivity(){const top=[...leads].sort((a,b)=>b.id-a.id).slice(0,4);$("activityList").innerHTML=top.map((l,i)=>`<div class="activity" style="animation-delay:${i*.05}s"><div class="activity-icon">${i===0?"+":"↗"}</div><div><strong>${i===0?t("activity.added"):t("activity.moved")}</strong><p>${l.name} · ${l.company} · ${t("stages."+l.stage)}</p></div></div>`).join("")}
function avatarPath(l){return l.avatar?`assets/avatars/${l.avatar}.svg`:"assets/avatars/amina.svg"}
function renderPriority(){const list=[...filteredLeads()].sort((a,b)=>b.value-a.value).slice(0,5);$("priorityTable").innerHTML=list.map(l=>`<tr><td><div class="lead-person"><img src="${avatarPath(l)}" alt=""><div><strong>${l.name}</strong><span class="muted">${l.email}</span></div></div></td><td>${l.company}</td><td><strong>${money(l.value)}</strong></td><td><span class="stage-pill">${t("stages."+l.stage)}</span></td><td>${l.owner}</td></tr>`).join("")}
function renderKanban(){const highOnly=$("pipelineFilter").value==="high",list=filteredLeads().filter(l=>!highOnly||l.value>=100000);$("kanbanBoard").innerHTML=stages.map(stage=>{const items=list.filter(l=>l.stage===stage),total=items.reduce((s,l)=>s+l.value,0);return `<div class="kanban-column" data-stage="${stage}"><div class="kanban-head"><h3>${t("stages."+stage)}</h3><span>${items.length} · ${money(total)}</span></div><div>${items.map(l=>`<article class="lead-card" draggable="true" data-id="${l.id}"><div class="lead-card-top"><div><h4>${l.name}</h4><p class="company">${l.company}</p></div><span class="score">${l.score}</span></div><div class="lead-value">${money(l.value)}</div><div class="lead-meta"><span>${l.email}</span><img class="mini-avatar" src="${avatarPath(l)}" alt=""></div></article>`).join("")}</div></div>`}).join("");
document.querySelectorAll(".lead-card").forEach(card=>{card.addEventListener("dragstart",()=>card.classList.add("dragging"));card.addEventListener("dragend",()=>{card.classList.remove("dragging");document.querySelectorAll(".kanban-column").forEach(c=>c.classList.remove("drag-over"))})});
document.querySelectorAll(".kanban-column").forEach(col=>{col.addEventListener("dragover",e=>{e.preventDefault();col.classList.add("drag-over")});col.addEventListener("dragleave",()=>col.classList.remove("drag-over"));col.addEventListener("drop",e=>{e.preventDefault();const card=document.querySelector(".lead-card.dragging");if(!card)return;const lead=leads.find(l=>l.id===Number(card.dataset.id));if(lead){lead.stage=col.dataset.stage;save();renderAll();showToast(t("toast.moved"))}})})}
function renderContacts(){const list=filteredLeads();$("contactGrid").innerHTML=list.length?list.map((l,i)=>`<article class="contact-card" style="animation-delay:${i*.04}s"><div class="contact-head"><img class="contact-avatar" src="${avatarPath(l)}" alt=""><div><h3>${l.name}</h3><p>${l.company}</p></div></div><div class="contact-details"><span>✉ ${l.email}</span><span>◈ ${t("stages."+l.stage)} · ${money(l.value)}</span></div></article>`).join(""):`<div>${t("contacts.noContacts")}</div>`}
function renderTasks(){$("taskList").innerHTML=tasks.length?tasks.map((task,i)=>`<article class="task-item ${task.done?"done":""}" style="animation-delay:${i*.04}s"><input class="task-check" type="checkbox" data-task-check="${task.id}" ${task.done?"checked":""}><div class="task-info"><h3>${task.title}</h3><p>${task.date}</p></div><button class="task-delete" data-task-delete="${task.id}">×</button></article>`).join(""):`<div class="panel">${t("tasks.noTasks")}</div>`}
function renderAll(){renderMetrics();renderFunnel();renderActivity();renderPriority();renderKanban();renderContacts();renderTasks()}
function openModal(id){$(id).classList.add("open")}function closeModal(id){$(id).classList.remove("open")}function openSidebar(){$("sidebar").classList.add("open");$("drawerOverlay").classList.add("open")}function closeSidebar(){$("sidebar").classList.remove("open");$("drawerOverlay").classList.remove("open")}
let toastTimer;function showToast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").classList.remove("show"),1800)}
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>setView(btn.dataset.view)));document.querySelectorAll("[data-go]").forEach(btn=>btn.addEventListener("click",()=>setView(btn.dataset.go)));
$("mobileMenu").addEventListener("click",openSidebar);$("drawerOverlay").addEventListener("click",closeSidebar);$("langEN").addEventListener("click",()=>setLanguage("en"));$("langPT").addEventListener("click",()=>setLanguage("pt"));
$("themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("clientflowTheme",document.body.classList.contains("dark")?"dark":"light")});
$("addLeadBtn").addEventListener("click",()=>openModal("leadModal"));$("addTaskBtn").addEventListener("click",()=>openModal("taskModal"));document.querySelectorAll("[data-close-modal]").forEach(btn=>btn.addEventListener("click",()=>closeModal(btn.dataset.closeModal)));
$("leadForm").addEventListener("submit",e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());leads.push({id:Date.now(),name:data.name,company:data.company,email:data.email,value:Number(data.value),stage:data.stage,owner:"Francisco",score:Math.floor(70+Math.random()*28),avatar:null});save();e.target.reset();closeModal("leadModal");renderAll();showToast(t("toast.lead"))});
$("taskForm").addEventListener("submit",e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());tasks.unshift({id:Date.now(),title:data.title,date:data.date,done:false});save();e.target.reset();closeModal("taskModal");renderTasks();showToast(t("toast.task"))});
document.addEventListener("click",e=>{const del=e.target.closest("[data-task-delete]");if(del){tasks=tasks.filter(x=>x.id!==Number(del.dataset.taskDelete));save();renderTasks();showToast(t("toast.deleted"))}});
document.addEventListener("change",e=>{const check=e.target.closest("[data-task-check]");if(check){const task=tasks.find(x=>x.id===Number(check.dataset.taskCheck));if(task)task.done=check.checked;save();renderTasks()}});
$("searchInput").addEventListener("input",e=>{search=e.target.value;renderPriority();renderKanban();renderContacts()});$("pipelineFilter").addEventListener("change",renderKanban);
document.querySelectorAll(".modal").forEach(modal=>modal.addEventListener("click",e=>{if(e.target===modal)closeModal(modal.id)}));document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal("leadModal");closeModal("taskModal");closeSidebar()}});
if(localStorage.getItem("clientflowTheme")==="dark")document.body.classList.add("dark");setLanguage(lang);setView("dashboard");
window.addEventListener("load",()=>setTimeout(()=>$("pageLoader").classList.add("hide"),350));